/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as RouteRouteImport } from './routes/route'
import { Route as publicSettionTimeoutRouteImport } from './routes/(public)/settion-timeout'
import { Route as publicNotFoundRouteImport } from './routes/(public)/not-found'
import { Route as publicMaintenanceRouteImport } from './routes/(public)/maintenance'
import { Route as publicLogoutRouteImport } from './routes/(public)/logout'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as publicAuthErrorRouteImport } from './routes/(public)/auth-error'
import { Route as AuthenticatedUsersRouteRouteImport } from './routes/_authenticated/users/route'
import { Route as AuthenticatedReportRouteRouteImport } from './routes/_authenticated/report/route'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as AuthenticatedReportIndexRouteImport } from './routes/_authenticated/report/index'
import { Route as AuthenticatedReportSearchIndexRouteImport } from './routes/_authenticated/report/search/index'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteRoute = RouteRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSettionTimeoutRoute = publicSettionTimeoutRouteImport.update({
  id: '/(public)/settion-timeout',
  path: '/settion-timeout',
  getParentRoute: () => rootRouteImport,
} as any)
const publicNotFoundRoute = publicNotFoundRouteImport.update({
  id: '/(public)/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const publicMaintenanceRoute = publicMaintenanceRouteImport.update({
  id: '/(public)/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLogoutRoute = publicLogoutRouteImport.update({
  id: '/(public)/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/(public)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAuthErrorRoute = publicAuthErrorRouteImport.update({
  id: '/(public)/auth-error',
  path: '/auth-error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRouteRoute = AuthenticatedUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportRouteRoute =
  AuthenticatedReportRouteRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportIndexRoute =
  AuthenticatedReportIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportRouteRoute,
  } as any)
const AuthenticatedReportSearchIndexRoute =
  AuthenticatedReportSearchIndexRouteImport.update({
    id: '/search/',
    path: '/search/',
    getParentRoute: () => AuthenticatedReportRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof RouteRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRoute
  '/report': typeof AuthenticatedReportRouteRouteWithChildren
  '/users': typeof AuthenticatedUsersRouteRoute
  '/auth-error': typeof publicAuthErrorRoute
  '/login': typeof publicLoginRoute
  '/logout': typeof publicLogoutRoute
  '/maintenance': typeof publicMaintenanceRoute
  '/not-found': typeof publicNotFoundRoute
  '/settion-timeout': typeof publicSettionTimeoutRoute
  '/report/': typeof AuthenticatedReportIndexRoute
  '/report/search': typeof AuthenticatedReportSearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof RouteRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRoute
  '/users': typeof AuthenticatedUsersRouteRoute
  '/auth-error': typeof publicAuthErrorRoute
  '/login': typeof publicLoginRoute
  '/logout': typeof publicLogoutRoute
  '/maintenance': typeof publicMaintenanceRoute
  '/not-found': typeof publicNotFoundRoute
  '/settion-timeout': typeof publicSettionTimeoutRoute
  '/report': typeof AuthenticatedReportIndexRoute
  '/report/search': typeof AuthenticatedReportSearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof RouteRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRoute
  '/_authenticated/report': typeof AuthenticatedReportRouteRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRouteRoute
  '/(public)/auth-error': typeof publicAuthErrorRoute
  '/(public)/login': typeof publicLoginRoute
  '/(public)/logout': typeof publicLogoutRoute
  '/(public)/maintenance': typeof publicMaintenanceRoute
  '/(public)/not-found': typeof publicNotFoundRoute
  '/(public)/settion-timeout': typeof publicSettionTimeoutRoute
  '/_authenticated/report/': typeof AuthenticatedReportIndexRoute
  '/_authenticated/report/search/': typeof AuthenticatedReportSearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/report'
    | '/users'
    | '/auth-error'
    | '/login'
    | '/logout'
    | '/maintenance'
    | '/not-found'
    | '/settion-timeout'
    | '/report/'
    | '/report/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/users'
    | '/auth-error'
    | '/login'
    | '/logout'
    | '/maintenance'
    | '/not-found'
    | '/settion-timeout'
    | '/report'
    | '/report/search'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/report'
    | '/_authenticated/users'
    | '/(public)/auth-error'
    | '/(public)/login'
    | '/(public)/logout'
    | '/(public)/maintenance'
    | '/(public)/not-found'
    | '/(public)/settion-timeout'
    | '/_authenticated/report/'
    | '/_authenticated/report/search/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RouteRoute: typeof RouteRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  publicAuthErrorRoute: typeof publicAuthErrorRoute
  publicLoginRoute: typeof publicLoginRoute
  publicLogoutRoute: typeof publicLogoutRoute
  publicMaintenanceRoute: typeof publicMaintenanceRoute
  publicNotFoundRoute: typeof publicNotFoundRoute
  publicSettionTimeoutRoute: typeof publicSettionTimeoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/settion-timeout': {
      id: '/(public)/settion-timeout'
      path: '/settion-timeout'
      fullPath: '/settion-timeout'
      preLoaderRoute: typeof publicSettionTimeoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/not-found': {
      id: '/(public)/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof publicNotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/maintenance': {
      id: '/(public)/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof publicMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/logout': {
      id: '/(public)/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof publicLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/auth-error': {
      id: '/(public)/auth-error'
      path: '/auth-error'
      fullPath: '/auth-error'
      preLoaderRoute: typeof publicAuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/report': {
      id: '/_authenticated/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AuthenticatedReportRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/report/': {
      id: '/_authenticated/report/'
      path: '/'
      fullPath: '/report/'
      preLoaderRoute: typeof AuthenticatedReportIndexRouteImport
      parentRoute: typeof AuthenticatedReportRouteRoute
    }
    '/_authenticated/report/search/': {
      id: '/_authenticated/report/search/'
      path: '/search'
      fullPath: '/report/search'
      preLoaderRoute: typeof AuthenticatedReportSearchIndexRouteImport
      parentRoute: typeof AuthenticatedReportRouteRoute
    }
  }
}

interface AuthenticatedReportRouteRouteChildren {
  AuthenticatedReportIndexRoute: typeof AuthenticatedReportIndexRoute
  AuthenticatedReportSearchIndexRoute: typeof AuthenticatedReportSearchIndexRoute
}

const AuthenticatedReportRouteRouteChildren: AuthenticatedReportRouteRouteChildren =
  {
    AuthenticatedReportIndexRoute: AuthenticatedReportIndexRoute,
    AuthenticatedReportSearchIndexRoute: AuthenticatedReportSearchIndexRoute,
  }

const AuthenticatedReportRouteRouteWithChildren =
  AuthenticatedReportRouteRoute._addFileChildren(
    AuthenticatedReportRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRoute
  AuthenticatedReportRouteRoute: typeof AuthenticatedReportRouteRouteWithChildren
  AuthenticatedUsersRouteRoute: typeof AuthenticatedUsersRouteRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRouteRoute: AuthenticatedDashboardRouteRoute,
  AuthenticatedReportRouteRoute: AuthenticatedReportRouteRouteWithChildren,
  AuthenticatedUsersRouteRoute: AuthenticatedUsersRouteRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  RouteRoute: RouteRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  publicAuthErrorRoute: publicAuthErrorRoute,
  publicLoginRoute: publicLoginRoute,
  publicLogoutRoute: publicLogoutRoute,
  publicMaintenanceRoute: publicMaintenanceRoute,
  publicNotFoundRoute: publicNotFoundRoute,
  publicSettionTimeoutRoute: publicSettionTimeoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
